### ISSUE TITLE
Kick from server

### ISSUE THREAD

**Issue by the-just-luke** [samipourquoi/every-scoreboard#4]
Anytime you try to view your own statistics through the escape menu you are kicked. I believe it possibly has something to do with multiconnect atleast for some people but nothing confirmed.

**Comment by Syntro42** [comment]
Hey. Every-scoreboard is just a datapack that runs commands when called, so it wouldn’t have an effect on accessing your statistic menu in-game. What other mods are you using besides Multiconnect? Old versions of Endtech Additions have that problem, so it could be that (if it’s only on the server and not on the client).
